# Generated by Django 5.1.1 on 2024-10-27 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_49', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
