# Generated by Django 5.1.1 on 2024-10-28 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_49', '0002_delete_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
