# Generated by Django 5.1.1 on 2024-10-28 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_49', '0005_department_connection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Connection',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
